### ISSUE TITLE
Does not work with Firmware EnglishDeutschMagyarRomanianCzech Firmware-Version: 01.02.068.11.EURO.SIP

### ISSUE THREAD

**Issue by Bruceforce** [diveflo/arris-tg3442-reboot#10]
Hi. Currently the script is not working with Firmware Version EnglishDeutschMagyarRomanianCzech
Firmware-Version: 01.02.068.11.EURO.SIP (which looks very similar to an already supported version despite of the SIP at the end)

**Comment by f-s** [comment]
Hello,

I use 01.02.068.11.EURO.SIP and its working?

Regards,

fse

**Comment by diveflo** [comment]
@Bruceforce did you have a chance to test it again?
If it's still not working could you tell me the output to the console that you receive? Unfortunately I don't have that specific version here to test, but with the console output I could at least see at which point it breaks.

**Comment by Bruceforce** [comment]
Hi. Just tested again with the latest docker Image. Output attached.

```
Traceback (most recent call last):


  File "/usr/src/app/arris-tg3442-reboot.py", line 89, in <module>


    modem = login(session, url, username, password)


  File "/usr/src/app/arris-tg3442-reboot.py", line 33, in login


    modem = get_firmware_handler(soup)


  File "/usr/src/app/firmware.py", line 25, in get_firmware_handler


    raise NotImplementedError("Did not detect any known firmware version - please open a GitHub issue with your firmware version")


NotImplementedError: Did not detect any known firmware version - please open a GitHub issue with your firmware version
```

**Comment by diveflo** [comment]
Hi,
I pushed a new docker image with the tag `sip`. Could you give that a try?
`docker pull floriang89/arris-tg3442-reboot:sip`

Thansk!
